### ISSUE TITLE
Issue when saving large number of file

### ISSUE THREAD

**Issue by marinlauber** [weymouth/WaterLily.jl#102]
This messes up the file name when we reach a large number of files (>100)

https://github.com/weymouth/WaterLily.jl/blob/888458479f62eb17282aedf822a46234b942a6d0/src/vtkWriter.jl#L39C41-L39C62

**Comment by b-fg** [comment]
Has this been fixed now?

**Comment by marinlauber** [comment]
This has been fixed by #106. I will close it now.
