### ISSUE TITLE
Vtk writer, writing always to vtk_data folder

### ISSUE THREAD

**Issue by ddeboerfluid** [weymouth/WaterLily.jl#103]
Currently the vtk writer always writes to the vtk_data folder. In case multiple simulations are done after each other, this will fill up the same folder with all the results. In the filename you can still specify which case it is, but it would be cleaner to have the option to specificy the folder where you would like the vti & pvd files to be stored

https://github.com/weymouth/WaterLily.jl/blob/888458479f62eb17282aedf822a46234b942a6d0/src/vtkWriter.jl#L16C66-L16C80

**Comment by b-fg** [comment]
Isn't `dir` just set so that a different path can be passed to the `vtkWriter` constructor??

**Comment by ddeboerfluid** [comment]
Yes you are right. Sorry I didn't realise this

**Comment by ddeboerfluid** [comment]
Still don't get it to work like I would like to, maybe I am doing something wrong. I would like to have my output folder structured like the following:

1. /Output/*casename*/vtk_data/ (here all the vti files of the fields should be saved)
2. /Output/*casename*/ (here the pvd file and other files I save myself should be written)

I use the following line:
wr      =   vtkWriter("fields"; dir="Output/"*case_name*"/vtk_data", attrib=custom_attrib)

This works with (1), but not with (2), as it saves the pvd file as fields.pvd in the working directory directly, and not in /Output/*casename*/ like I would want to.

**Comment by b-fg** [comment]
Uhm... the `vtkWriter` can only have a single output directory. So you can only expect that output files will be written in `dir`. I am not sure what is it that is not working for you.

**Comment by b-fg** [comment]
cc @marinlauber

**Comment by marinlauber** [comment]
@ddeboerfluid To obtain the behavior you describe, run each script within the `/Output/casename/` and use the standard writer constructor. The `field` is only to name the `.pvd` file, it's not used to set the file path.

If you want to run multiple cases, just change the `field` name to `case_1`, `case_2` etc. They will all be stored in the same place but you will have different `pvd` files.

**Comment by marinlauber** [comment]
> @ddeboerfluid Did you try setting `fields` to `/Output/casename/fields`? You will have to create the directory `Output/casename/` first, so it's probably not a good option.
> 
> Can you not just run a standard `vrtWriter` from the `/Output/casename/` folder?

I tried the first approach and it doesn't work. I had a quick look and there is no simple and general way to get the behavior you want. What I suggest is that you run from `/Output/casename/` to get the desired behavior.

**Comment by ddeboerfluid** [comment]
I will just change 'fields'  to 'fields_*i*' where i refers to which case it is. Then everything will be stored in the correct folders and the pvd file will be in the general folder, but I can see which one is which. Thanks for your help!
