### ISSUE TITLE
Test fail on MacOS in testing enviroment

### ISSUE THREAD

**Issue by weymouth** [weymouth/WaterLily.jl#104]
I can replicate the error mentioned in #98 and #95 on MacOS, if I run the test suite using 
`] test`
but not if I run the tests from the REPL. I guess that means there is something in a normal build which is not being replicated in the testing environment. 

In the test environment, I've tracked this down to a NaN cropping up in the Vcycle.

**Comment by weymouth** [comment]
Should be fixed with https://github.com/weymouth/WaterLily.jl/commit/b267c6bc691a20984cae3e15b8afda699b7525f7

**Comment by b-fg** [comment]
Great, thanks! Will merge in my PRs.
