### ISSUE TITLE
Courant number (CFL)

### ISSUE THREAD

**Issue by meysamrajabi95** [weymouth/WaterLily.jl#109]
Hi,
I have an issue with having too much noise for the force signal acting on a body. I want to know how can I change/optimize the CFL number here [https://github.com/weymouth/WaterLily.jl/blob/master/src/Flow.jl#L165] ?  ? what are these 0.5 showing in these lines: 
```
    BDIM!(a); scale_u!(a,0.5); BC!(a.u,U,a.exitBC,a.perdir)
    project!(a,b,0.5); BC!(a.u,U,a.exitBC,a.perdir)
```

**Comment by marinlauber** [comment]
Hi @meysamrajabi95, 

To adjust the CFL, you can overwrite the `WaterLily.CFL` function to limit the maximum value based on your criterion. This would look something like with `1.234` replaced by your desired CFL value. (This goes into your main script)
```Julia
WaterLily.CFL(a::Flow) = WaterLily.CFL(a;Δt_max=1.234)
```
For your second question, this is just the classical scaling of the corrector step; see [here](https://en.wikipedia.org/wiki/Predictor%E2%80%93corrector_method#:~:text=Next%2C%20the%20corrector%20step%3A%20improve%20the%20initial%20guess%20using%20trapezoidal%20rule)

**Comment by meysamrajabi95** [comment]
Great. Thank you!
