### ISSUE TITLE
Change default time in force integration

### ISSUE THREAD

**Issue by marinlauber** [weymouth/WaterLily.jl#110]
In the pressure [force integration](https://github.com/marinlauber/WaterLily/blob/33421ae7b53143c58c7741aced9461fecca44fc4/src/Metrics.jl#L83) the default is to use `t=0` for the body position, but this doesn't correspond to the pressure, which is stored at `time(sim)`.

I think the default behavior should be to measure the body at `time(sim)`, where the pressure is also defined. This would require passing `sim` or `flow` directly to the function.

**Comment by b-fg** [comment]
Sure, make a PR and I will review it :)

**Comment by weymouth** [comment]
Did this get done?

**Comment by marinlauber** [comment]
No, I haven't done it. I am not sure how to pass the correct time to the function without changing the function arguments.
