### ISSUE TITLE
Taylor Vortex file

### ISSUE THREAD

**Issue by tiinaroose** [weymouth/WaterLily.jl#115]
Sorry, I am a beginner with this. I downloaded everything including CUDA, but when I attempt to run this Taylor Vortex thing I get this error message. What am I doing wrong.

ERROR: AssertionError: CUDA.functional()
Stacktrace:
 [1] top-level scope
   @ ~/Documents/Julia-March-24/Tiina-WL-2.jl:18

**Comment by b-fg** [comment]
What steps did you follow to download and install? Also, do you have a NVIDIA GPU in your system? If you are trying to run with `CuArray` backend but you do not have such GPU, this error will show up. Even if you have CUDA installed (it is possible to have it installed in system without GPU)  if does not mean that CUDA is functional, hence the error.

**Comment by weymouth** [comment]
Was that the issue Tiina?
