### ISSUE TITLE
Write VTK size/shape of field in writer

### ISSUE THREAD

**Issue by ddeboerfluid** [weymouth/WaterLily.jl#116]
https://github.com/weymouth/WaterLily.jl/blob/52a66f3c8318328e50d8877107f3b2da3f718c28/ext/WaterLilyWriteVTKExt.jl#L58

Is it possible to change this line to:
k = w.count[1]; N=size(w.output_attrib["p"](a))

I think that should work generally and gives cleaner vti files (in case you decided to crop the fields before saving for example)

**Comment by b-fg** [comment]
@marinlauber

**Comment by marinlauber** [comment]
I think the default `write!()` should stay as is @ddeboerfluid, the idea is just to dump some fields to a `vti`. Also, this will make it non trivial to restart from a `vti`.
You can define your own write function for your specific file IO cases and use that in your code.
