### ISSUE TITLE
Can WaterLily.jl be used for 2D hydrodynamic modeling of real watersheds, similar to lisflood-fp, mike21, and anuga?

### ISSUE THREAD

**Issue by chooron** [weymouth/WaterLily.jl#124]
I want to use the Julia language for 2D hydrodynamic modeling and apply it to real rivers, but I don't know how to input DEM data of the river into WaterLily.jl and perform simulation.

**Comment by b-fg** [comment]
Maybe relevant: https://github.com/milankl/ShallowWaters.jl
