### ISSUE TITLE
Confusion with the Circle Tutorial and Unicode Characters 

### ISSUE THREAD

**Issue by werzum** [weymouth/WaterLily.jl#14]
Hello,
first up thanks for this package, it looks really interesting. 
When I was following the first code example, I stumbled upon some weird errors in Julia even though my code seemed literally the same. Upon using a code diff checker I noted that the "v" used in the example is not the latin "v" (U+0076) but the greek nu (U+03BD), which tripped up my code which was half typed by me and half copied from the example.
 I guess the usage of the greek nu is intended to denote the correct formula symbol, but I would suggest to add a clarification in the tutorial to prevent confusion with these letters without optical differences.
Cheers, Carlo

**Comment by weymouth** [comment]
Good catch!
