### ISSUE TITLE
Use KernelAbstractions for loops?

### ISSUE THREAD

**Issue by glwagner** [weymouth/WaterLily.jl#18]
Using a combination of KernelAbstractions and broadcasting should make the code GPU compatible and multithreaded without much additional effort.

https://github.com/JuliaGPU/KernelAbstractions.jl

KernelAbstractions can also help catch a few other performance gotchas, like a failure to use fused multiply-add instructions by default:

https://www.juliabloggers.com/optimizing-julia-code-improving-the-performance-of-entropy-conservative-dg-methods-in-trixi-jl/

**Comment by weymouth** [comment]
Thanks Gregory! I'm more than happy to get tips on this front.

I made the changes today to get all the loops working at top speed for Julia 1.6 - but hopefully this will align well with your suggestion.

**Comment by b-fg** [comment]
We are working on this again and indeed using `@index(Global, Cartesian)`. A lot has been ported already but we have not finished yet. You can check the developments in the [CUDA branch](https://github.com/weymouth/WaterLily.jl/tree/CUDA) if interested :)
