### ISSUE TITLE
Saving each time step flow field values

### ISSUE THREAD

**Issue by vahhab1370** [weymouth/WaterLily.jl#30]
I don't know much about Julia. What I want to have from the simulation of a flow over a cylinder is extracting the full field of velocity and vorticity for a specific time duration. In other words, I want to save some arrays like [T,n,m], T as time steps, M and N as spatial domains. Could you please help me how can I do that?

using WaterLily
using LinearAlgebra: norm2
Re=250
n=3*2^7
m=2^8
radius=m/6
center, ν = m/2, radius/Re
body = AutoBody((x,t)->norm2(x .- center) - radius)
sim=Simulation((n+2,m+2), [1.,0.], radius; ν, body)
sim_step!(sim,10)
using MATLAB
write_matfile("Desktop\\test_u.mat";sim.flow.u)
vrtx=sim.flow.σ
write_matfile("Desktop\\test_vrtx.mat";vrtx)

Also,  is "sim.flow.σ" vorticity of flow?

Any help would be appreciated.

Thank you!

**Comment by weymouth** [comment]
You just need to loop over a set of smaller steps and output within that loop. You could take a look at the example for making a gif in TwoD_Julia.jl:

```
t = range(0.,stop;step=0.3)
gr(show = false, size=(700,600))
for tᵢ in t
    sim_step!(sim,tᵢ)
    ### print stuff out here ###
end
````

**Comment by weymouth** [comment]
I missed the second question. `sim.flow.σ` is just a blank array that you can fill with anything you want. In that same TwoD_Julia.jl function, I use `WaterLily.curl` to fill it with the vorticity. I've added that to the example above.

**Comment by vahhab1370** [comment]
Thank you so much!
