### ISSUE TITLE
circle position

### ISSUE THREAD

**Issue by vahhab1370** [weymouth/WaterLily.jl#31]
Hello again,

I am wondering how to define the position of the circle as:

x= a y=b, where a and be are not the same

n=3*2^7
m=2*2^7
radius=m/6
center, ν = m/2, radius/Re
body = AutoBody((x,t)->norm2(x .- center) - radius)
sim=Simulation((n+2,m+2), [1.,0.], radius; ν, body)

with this code, x=y=m/6

Thank you

**Comment by weymouth** [comment]
This isn't really a WaterLily issue, you just need to learn about tuples work in Julia. Just use `center = (a,b)`.
