### ISSUE TITLE
Adjusting for Surface Mesh

### ISSUE THREAD

**Issue by jvaverka** [weymouth/WaterLily.jl#32]
Hi, cool package and very nice work on WaterLily.jl!

In the JuliaCon 2021 talk it is mentioned that importing a surface mesh is a fairly easy adjustment. However, I am having a go at it and could use more insight. My goal is to perform an apropos [Santa's Sleigh CFD visualization](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.iqvNEg20Bh_28dY179A9YgHaFj%26pid%3DApi&f=1). Figured out how to import the geometry, but the next step is confusing me.

Can AutoBody be used in conjunction with the surface mesh? If so then how does `sdf` and `map` come into play? Or should I consider making a new struct (something like `MeshBody`) when dealing with imported geometries?

Part of my confusion comes down to not fully understanding the following code from the 3D Donut example below. Maybe someone can elaborate.

```
body = AutoBody() do xyz,t
    x,y,z = xyz - center
    norm2([x,norm2([y,z])-R])-r
end
```

**Comment by weymouth** [comment]
That sounds like a super fun idea. 

The code you have there is the analytic distance function from any point `xyz` to the surface of a torus with ring radius `R` and cross section radius `r`. The `AutoBody` struct requires this kind of analytic distance function, and so it can't handle a surface mesh out of the box. 

My plan for importing mesh geometries was to use one of the existing geometry/meshing packages in Julia to produce a distance function and then proceed as usual. Unfortunately, it seems like some of the packages aren't being maintained. (The main issue with OS projects). I opened a few issues, but I haven't picked it back up in quite a while:
 - https://github.com/rdeits/AdaptiveDistanceFields.jl/issues/15
 - https://github.com/JuliaGeometry/GeometryBasics.jl/pull/148
 - https://github.com/JuliaRobotics/EnhancedGJK.jl/issues/39

**Comment by weymouth** [comment]
We've decided to go with Parametric bodies instead of meshes for now. I'm not opposed to someone adding a STLBodies package at some point in the future, but regardless, it's not an issue with this package. So I am going to close this issue.
