### ISSUE TITLE
README.md needs update? MethodError: no method matching sim_step!(::Simulation; t_end::Int64)

### ISSUE THREAD

**Issue by mgr327** [weymouth/WaterLily.jl#50]
An attempt to run the exact code from the example 'Flow over a circle' in README.md produces the following error:

```
julia> sim_step!(circ,t_end=10)
ERROR: MethodError: no method matching sim_step!(::Simulation; t_end::Int64)

Closest candidates are:
  sim_step!(::Simulation, ::Any; verbose, remeasure) got unsupported keyword argument "t_end"
   @ WaterLily ~/.julia/packages/WaterLily/rv3IZ/src/WaterLily.jl:83

```
It seems README.md needs updating

**Comment by weymouth** [comment]
Oops. Missed that one!

Gabriel D Weymouth
_______________________________________________
"Computers are useless. They can only give you answers." Pablo Picasso
