### ISSUE TITLE
Integration with Flux

### ISSUE THREAD

**Issue by andferrari** [weymouth/WaterLily.jl#52]
Thank you for this nice package!

I am trying to use `Flux.jl` together with a simulation, but Zygote complains with
`Mutating arrays is not supported -- called copyto!(Array{Float32, 3}, ...)`

Thank you for your help

A toy example is:
```
using WaterLily, Flux

sim = Simulation((32, 32), (0, 0), 5; U=1, ν=1e-4, T=Float32)
model = Conv((3,3), 2 => 2; pad=SamePad() )

function comploss(model, sim) 
    t₀ = round(sim_time(sim))
    loss = 0.0
    for tᵢ in range(t₀, t₀+1; step=0.1)
        sim_step!(sim,tᵢ; remeasure=false)
        sim.flow.u .+= model(sim.flow.u[:,:,:,:])[:,:,:]
        loss += sum(sim.flow.u.^2)
    end
    return loss
end

grad = gradient(m -> comploss(m, sim), model)
```

**Comment by weymouth** [comment]
Yes, this is an issue with Flux. Enzyme will potentially enable backwards AD through mutating arrays, but I haven't tried it yet.

**Comment by andferrari** [comment]
Thank you for your help. 
I gave it a quick try but it does not seems that Enzyme integrates easily in Flux.

**Comment by atiyo** [comment]
Maybe ReverseDiff.jl will work?

**Comment by andferrari** [comment]
I tried:
```
using WaterLily, Flux
using ReverseDiff

sim = Simulation((32, 32), (0, 0), 5; U=1, ν=1e-4, T=Float32)
model = Conv((3,3), 2 => 2; pad=SamePad() )

pars, re = Optimisers.destructure(model)

function comploss(pars, re, sim) 
    nn = re(pars)
    t₀ = round(sim_time(sim))
    loss = 0.0
    for tᵢ in range(t₀, t₀+1; step=0.1)
        sim_step!(sim,tᵢ; remeasure=false)
        sim.flow.u .+= nn(sim.flow.u[:,:,:,:])[:,:,:]
        loss += sum(sim.flow.u.^2)
    end
    return loss
end

g = ReverseDiff.gradient(θ->comploss(θ, re, sim), pars)
```
but it terminates with 
```
askFailedException

    nested task error: UndefRefError: access to undefined reference
    Stacktrace:
```

**Comment by weymouth** [comment]
@b-fg Have you looked at this?

**Comment by b-fg** [comment]
Not yet. I want to give this a proper look but I do not have the time at the moment, sorry. How was AD implemented in the data-driven GMG though? And, would that be portable here?

**Comment by weymouth** [comment]
That was ForwardDiff.

**Comment by weymouth** [comment]
ForwardDiff is now working with master from #129. ReverseDiff seems to require hand-written kernels, and could only work over a single time step. Should we close this as "as good as it'll get"?

**Comment by b-fg** [comment]
Yeap, I think this issue is solved, but we can open one for AD on GPU.
