### ISSUE TITLE
Simulations of wing-like structures always have detached flow

### ISSUE THREAD

**Issue by tdunning** [weymouth/WaterLily.jl#56]
In trying to simulate a crude wing in 2-D, I always seem to have flow that detaches from the top of the wing. This happens with low and high reynolds numbers and with low and high viscosities and very low angle of attack.

Could you help me build a simple example that does this correctly?

Here is an example:

![image](https://github.com/weymouth/WaterLily.jl/assets/250490/8d9890e3-1ada-49d0-9854-35fbae50fe46)

**Comment by weymouth** [comment]
This depends sensitively on the foil shape and on the resolution of the flow. I suggest implementing a real foil shape and then reproducing some test cases from previous research papers. [Here's one example](https://www.sciencedirect.com/science/article/abs/pii/S0045782514003168), but there are lots and lots.

**Comment by weymouth** [comment]
Here's the proteins of the paper. https://eprints.soton.ac.uk/369635/1/Maertens2014%2520CMAME.pdf

**Comment by tdunning** [comment]
This looks very promising

**Comment by weymouth** [comment]
Note that 2D simulations at low Re _should_ give separated flow.
[image: image_360.png]
[image: image_480.png]

High Re flow is always 3D, if you don't run a 3D simulation at high Re, you
will get something like this
[image: image.png]
Attached, but weird.

Gabriel D Weymouth
_______________________________________________
"Computers are useless. They can only give you answers." Pablo Picasso

**Comment by weymouth** [comment]
Note that 2D simulations at low Re _should_ give separated flow.
![image](https://github.com/weymouth/WaterLily.jl/assets/468263/d7135959-a108-444f-8659-cb9e3dae5402)
![image](https://github.com/weymouth/WaterLily.jl/assets/468263/ad0b7c0d-16c3-4a9c-970e-065a47c777ad)


High Re flow is always 3D, if you don't run a 3D simulation at high Re, you
will get something like this
![image](https://github.com/weymouth/WaterLily.jl/assets/468263/37025e3d-c20b-4b72-b536-b9d1682edc84)

Attached, but weird.

Gabriel D Weymouth
