### ISSUE TITLE
Particle flows visualization

### ISSUE THREAD

**Issue by tdunning** [weymouth/WaterLily.jl#57]
I have adapted the TwoBody_circle example to use a different shape. The flow seems to penetrate into the body. 

Is this a problem?

![image](https://github.com/weymouth/WaterLily.jl/assets/250490/4edcdaae-d483-4c67-ac3a-db173a57c98a)

**Comment by weymouth** [comment]
If you want to check flow penetration, you should plot the normal velocity component, not the vorticity.

**Comment by tdunning** [comment]
Is that because the vorticity is effectively smoothed a bit?

Perhaps the question I really had was what is the best way to visualize flow around a shape like this? Is there an example of how to insert tagged particles (aka smoke)?

**Comment by tdunning** [comment]
Great suggestion!

Thanks.

Would you like to have me file a pull request with an example resulting from this effort?

**Comment by tdunning** [comment]
Hmmm... that article looks excellent except that all of the good bits are paywalled. Do you have a preprint copy? Or is the source code for the results that you present in sections 3.1 and 3.2 available?

Again, these seem like they would make very good examples to include in WaterLily. Happy to do the (small compared to what you have done) work to prepare those.

**Comment by weymouth** [comment]
Good point. I'll revise that link in the other issue.

That paper was done using an older Fortran code. Waterlily is a new implementation of the same method in Julia.

**Comment by weymouth** [comment]
> Is that because the vorticity is effectively smoothed a bit?
> 
> Perhaps the question I really had was what is the best way to visualize flow around a shape like this? Is there an example of how to insert tagged particles (aka smoke)?

Not yet. That would be a nice addition. Possibly, we should have a separate flow visualization folder with metrics.jl and other efforts such as this suggestion.

**Comment by weymouth** [comment]
I made a new repo with a tracer `Particles` class which can be used for visualization. There are two fun example plots in the repo for making pathline and dynamic vector field plots.
