### ISSUE TITLE
Heaving Cylinder in still water

### ISSUE THREAD

**Issue by Dagau** [weymouth/WaterLily.jl#67]
Hello,
Thanks a lot for the work done for this package, it is very intuitive and easy to compute three-dimensional flows on my laptop.

For my work, I need to assess the inertial forces on a heaving cylinder in still water for a large number of conditions (hence my interest in fast simulations!). I could easily realise simulations of a moving cylinder with a constant inflow velocity.
However, I encountered two main problems when attempting to do it in still water:
   - 1) I get confused with the non-dimensional time as it seems to rely on the inlet fluid velocity. When the inflow velocity is set to 0, the simulation gets stuck at the first time-step. How are we meant to progress the simulation forward in time with no inflow velocity?
   - 2) Additionally, is it possible to set all the domain boundaries as outlets?

Many thanks for your help!

**Comment by weymouth** [comment]
1) The user can always set the velocity scale they want in a [`Simulation`](https://weymouth.github.io/WaterLily.jl/dev/#WaterLily.Simulation). The default argument is `U=norm2(u_BC)`, but this doesn't work is there is no background flow. Just pass it the representative velocity scale of the motion instead. 
2) There is an open issue #54 about domain BCs. Currently, the only option is a symmetry plane. But [there is a branch with periodic conditions implemented](https://github.com/TzuYaoHuang/WaterLily.jl) and [I am considering](https://twitter.com/gabrielweymouth/status/1676575220457455617) "external" BCs as well.
