### ISSUE TITLE
Jellyfish example: contour not exported by GLMakie

### ISSUE THREAD

**Issue by asjir** [weymouth/WaterLily.jl#71]
I think [here](https://github.com/weymouth/WaterLily.jl/blob/3caf8b03c429aaeca6f245c4016aa328c2934734/examples/ThreeD_jelly.jl#L58) it should be changed to GLMakie.contour.

**Comment by asjir** [comment]
also I noticed: [this line in Shark example](https://github.com/weymouth/WaterLily.jl/blob/3caf8b03c429aaeca6f245c4016aa328c2934734/notebooks/Shark.jl#L247) doesn't work. I don't know how it's supposed to work, but I just wrote:
```julia
		flowsize = size(sim.flow.p)
		df_ = ones(Float32, tuple(flowsize..., length(flowsize)))
        return WaterLily.∮nds(sim.flow.p, df_ ,sim.body, t * sim.L / sim.U) ./ (0.5 * sim.L * sim.U^2)
```
and it seems to work now.

**Comment by weymouth** [comment]
> I think [here](https://github.com/weymouth/WaterLily.jl/blob/3caf8b03c429aaeca6f245c4016aa328c2934734/examples/ThreeD_jelly.jl#L58) it should be changed to GLMakie.contour.

If you have imported something else with the function `contour`, then you will need to write it as you have. From a fresh start, the line used to work fine, but perhaps `GLMakie` has stopped exporting that function??

**Comment by weymouth** [comment]
> also I noticed: [this line in Shark example](https://github.com/weymouth/WaterLily.jl/blob/3caf8b03c429aaeca6f245c4016aa328c2934734/notebooks/Shark.jl#L247) doesn't work. I don't know how it's supposed to work, but I just wrote:
> 
> ```julia
>     function get_force(sim, t)
>         sim_step!(sim, t, remeasure=true)
> 		flowsize = size(sim.flow.p)
> 		df_ = ones(Float32, tuple(flowsize..., length(flowsize)))
>         return WaterLily.∮nds(sim.flow.p, df_ ,sim.body, t * sim.L / sim.U) ./ (0.5 * sim.L * sim.U^2)
>     end
> ```
> 
> and it seems to work now.

Cool. The integral function is currently being refactored and validated. I'll keep this issue open to remind me to update this example once that PR is merged.
