### ISSUE TITLE
Fluid Structure Interaction

### ISSUE THREAD

**Issue by jwethan** [weymouth/WaterLily.jl#75]
I've been experimenting in WaterLily with heaving airfoils recently and I'm interested in implementing leading-edge flexibility via a torsional spring model.  Is fluid structure interaction feasible with WaterLily? Has any work been done on coupling body displacement/dynamics with fluid forcing? I'm newer to Julia and WaterLily any advice would be appreciated. 

Thanks for this great package!

**Comment by weymouth** [comment]
@marinlauber is working on this capability right now. You can look at this PR https://github.com/weymouth/ParametricBodies.jl/pull/2 for the geometry part, but the "finite element" part is in another repo still under development.
