### ISSUE TITLE
MultiLevelPoisson solver tolerance not independent of domain size

### ISSUE THREAD

**Issue by marinlauber** [weymouth/WaterLily.jl#96]
I just realized (while looking at pressure forces) that the pressure field oscillates when the domain is large (384,256), see attached script.

I have managed to track the issue to the `MultiLevelPoisson/solver!` function.
This is linked to the V-cycle criterion that checks if the residual on the upper level (`r₂`) is below a certain tolerance (`tol`) before performing the Vcycle 
```
while r₂>tol && nᵖ<itmx
      Vcycle!(ml)
      smooth!(p); r₂ = L₂(p)
      log && push!(res,r₂)
      nᵖ+=1
end
```
The issue is that (`r₂`) depends on the grid size through `p.r` as `L₂(p::Poisson) = p.r ⋅ p.r`, while `tol` does not. This means that in some cases, the `solver!` doesn't perform any V-cycle, which doesn't change the pressure field.

The proposed solution is to scale the `tol` by the grid size, compute it once and store in in the `MultiLevelPoisson` structure, see #97
[TwoD_circle_pressure_check.zip](https://github.com/weymouth/WaterLily.jl/files/13877643/TwoD_circle_pressure_check.zip)

**Comment by weymouth** [comment]
Oops! This is what we do in the Fortran code. Not sure how we got away without doing it in WaterLily...
